### ISSUE TITLE
Country input

### ISSUE THREAD

**Issue by stop5** [vbresan/VAT_Calculator#3]
Since we can't add new countries and their VAT an textinput makes no sense. An spinner like the vat itself would make more sense.

**Comment by vbresan** [comment]
The idea is that the app has up to date liste of countries and their VAT rates, without any need for users to add them. The list of countries and rates is available [here](https://github.com/vbresan/VAT_Calculator/blob/master/app/src/main/assets/rates.json), and you are welcome to contribute.

Currently, there are 168 countries with VAT, and a spinner like the one for rates would not make any sense. For that reason TextInput with autocomplete (which actually acts as a spinner with text filtering) is implemented.
